### PR TITLE
Disable Werror for QEMU to increase succesful compilation probability

### PR DESCRIPTION
**Pull request by SweetVishnya**
This one is essential to build with newer clang

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@SweetVishnya not the maintainer, but I highly recommend put put a similar PR in symcc, same issue there :)

**Comment by SweetVishnya** [comment]
Seems like it is not as straightforward with SymCC. Just editing the README is not enough) So, I leave it for @sebastianpoeplau )

**Comment by vanhauser-thc** [comment]
I added it to my PR -> https://github.com/eurecom-s3/symcc/pull/46 but have still to check if it works, and no clue if the PR will be accepted ;)

**Comment by sebastianpoeplau** [comment]
Sorry guys, I'm a bit overwhelmed at the moment with little time for SymCC and SymQEMU. Thanks a lot for you contributions though, they're much appreciated and I'm trying to review and merge them as soon as possible.

**Pull request merged**
