### PR TITLE
Update to QEMU v8.2.2

### PR DESCRIPTION
**Pull request by rmalmain**
The compilation of `arm-linux-user` and `aarch64-linux-user` does not work because of the symqemu unit tests not linking correctly.
Maybe you could have a look @aurelf ?
It happens when configuring with this for example:
```bash
../configure                                                    \
      --audio-drv-list=                                           \
      --disable-sdl                                               \
      --disable-gtk                                               \
      --disable-vte                                               \
      --disable-opengl                                            \
      --disable-virglrenderer                                     \
      --disable-werror                                            \
      --target-list=arm-linux-user
```
Should we add 32-bit targets to the Dockerfile to make sure it compiles correctly in the future?  We could add `i386-linux-user` and `arm-linux-user` for example. Also, is there a reason why `aarch64` is not added to the Dockerfile? It seems to compile correctly with the small patch of this PR.

### CODE REVIEW

**Comment by rmalmain** [comment]
Oh, sorry for the duplicate. I already added a PR with these fixes in the past, but I completely forgot about it.
The problem with the linking is the same, though.

**Comment by aurelf** [comment]
Thanks, I'll have a look. Probably we can merge that, and then add the tests for the other arch to the docker and work on the fixes there?

**Comment by aurelf** [comment]
I don't have a problem with linking but segfault with i386.

``` 
Thread 1 "check-sym-runti" received signal SIGSEGV, Segmentation fault.
_sym_read_memory (addr=<optimized out>, length=length@entry=8, little_endian=little_endian@entry=true) at ../subprojects/symcc-rt/src/RuntimeCommon.cpp:152
152	  return std::accumulate(shadow.begin_non_null(), shadow.end_non_null(),
(gdb) bt
#0  _sym_read_memory (addr=<optimized out>, length=length@entry=8, little_endian=little_endian@entry=true) at ../subprojects/symcc-rt/src/RuntimeCommon.cpp:152
#1  0x0000555555576c2f in sym_load_guest_internal (env=env@entry=0x7fffffff8fe0, addr=addr@entry=4294953504, addr_expr=addr_expr@entry=0x0, load_length=load_length@entry=8, 
    result_length=result_length@entry=8 '\b', mmu_idx=0) at ../accel/tcg/tcg-runtime-sym.c:307
#2  0x0000555555576c7b in helper_sym_load_guest_i64 (env=env@entry=0x7fffffff8fe0, addr=addr@entry=140737488341536, addr_expr=addr_expr@entry=0x0, length=length@entry=8, 
    mmu_idx=mmu_idx@entry=0) at ../accel/tcg/tcg-runtime-sym.c:326
#3  0x000055555556687c in load_store_guest_test () at ../tests/unit/check-sym-runtime.c:297
#4  0x00007ffff7ea6584 in test_case_run (path=<optimized out>, test_run_name=0x555555742570 "/sym/load_store_guest", tc=0x5555556dc380) at ../glib/glib/gtestutils.c:2988
#5  g_test_run_suite_internal (suite=suite@entry=0x5555556db1f0, path=0x0) at ../glib/glib/gtestutils.c:3090
#6  0x00007ffff7ea64ab in g_test_run_suite_internal (suite=suite@entry=0x5555556db160, path=path@entry=0x0) at ../glib/glib/gtestutils.c:3109
#7  0x00007ffff7ea6a8a in g_test_run_suite (suite=suite@entry=0x5555556db160) at ../glib/glib/gtestutils.c:3189
#8  0x00007ffff7ea6b12 in g_test_run () at ../glib/glib/gtestutils.c:2275
#9  g_test_run () at ../glib/glib/gtestutils.c:2262
#10 0x0000555555562479 in main (argc=<optimized out>, argv=<optimized out>) at ../tests/unit/check-sym-runtime.c:409
```

**Comment by aurelf** [comment]
OK, I'll merge this and we will address other architectures problems in other PRs

**Pull request merged**
