### PR TITLE
Port to QEMU8

### PR DESCRIPTION
**Pull request by damienmaier**
Hello ! This is my port of SymQEMU to QEMU 8.1.

The merge commit message gives some information about what adaptations I performed. There is also some detailed explanations about potential problems in section 5.1 of my [bachelor thesis](https://dmaier.ch/bachelor-thesis.pdf).

### CODE REVIEW

**Comment by aurelf** [comment]
Thank you for the PR!
@sebastianpoeplau I propose that we create a branch with the current 4.1.1 version, so this remain easily available, maybe with a warning that there is no planned support? 
Then we merge this PR in the master branch, OK for you ? 
@damienmaier : you also had some automated testing code, this is not part of this PR, right?  It would be nice to have those tests that we could also use as GitHub actions.

**Comment by damienmaier** [comment]
Yes the automated tests are coming, I will do an other PR

**Comment by sebastianpoeplau** [comment]
Very well documented @damienmaier, and thanks for all the work!

> @sebastianpoeplau I propose that we create a branch with the current 4.1.1 version, so this remain easily available, maybe with a warning that there is no planned support? Then we merge this PR in the master branch, OK for you ?

Sounds like a good plan :+1:

**Comment by aurelf** [comment]
I could tests on my side and all looks good to me, thanks a lot Damien for your work !

**Pull request merged**
