### PR TITLE
SymQEMU tests and Dockefile

### PR DESCRIPTION
**Pull request by damienmaier**
The goal of this PR is to have an automated testing of SymQEMU that runs it on a known binary and checks that it outputs the expected results.

This is WIP but you can already check what I have.

For now this PR contains the script for running SymQEMU on a simple test program, and a Dockerfile that compiles SymQEMU and runs the test.

Instead of compiling SymCC during the image build, I think it makes more sense to rely on the existing docker image for SymCC and extract from it the needed .so file. This way, if the commands needed for compiling SymCC change in the future, only the Dockerfile of SymCC will need to be updated.

### CODE REVIEW

**Comment by aurelf** [comment]
Sorry for the inconvenience, this was closed by a GH action that came from the merge of QEMU, and it seems that while I can unlock I cannot reopen the PR (it seems to be not possible: https://github.com/isaacs/github/issues/361)
Can you redo a PR for this and #40 ?

**Comment by aurelf** [comment]
Also it seems this PR is on top of #38 ? I thought of merging #38 once we have the tests, but maybe it's easier to merge #38 first?

**Comment by damienmaier** [comment]
We can do this one before #38, this is a mistake on my side, I will submit a new PR tomorrow

**Comment by aurelf** [comment]
> Instead of compiling SymCC during the image build, I think it makes more sense to rely on the existing docker image for SymCC and extract from it the needed .so file. This way, if the commands needed for compiling SymCC change in the future, only the Dockerfile of SymCC will need to be updated.

In fact in the future maybe we should get SymCC to push a docker image (to Docker Hub or GitHub Packages) and use that one, so we don't even recompile it here. 

> We can do this one before #38, this is a mistake on my side, I will submit a new PR tomorrow

Great, thanks !

**Pull request closed without merging**
